### ISSUE TITLE
Local VPN tunneling

### ISSUE THREAD

**Issue by sdgros01** [osy/Jitterbug#51] opened 2022-04-17 05:13 UTC
Is there anything in the works to get single device VPN tunneling back working again on a paid developer account?

**Comment by disclaimer8** [comment] 2022-04-21 11:28
same for me, didnt work with paid acc

**Comment by iMonZ** [comment] 2022-05-03 06:01
Same

**Comment by osy** [comment] 2022-05-04 23:46
I'm going to mark this as duplicate due to a lack of information. I'm assuming it's the same underlying issue.

**Comment by osy** [comment] 2022-05-04 23:46
Duplicate of #42

**Closed by osy** 2022-05-04 23:46 UTC
Labels: duplicate

**Comment by esgie** [comment] 2022-05-19 22:04
I have faced similiar issue to the one described above on iPad Pro 2nd gen since updating to 15.4.1 (but I have skipped 15.4 so I can’t say about it). This isn’t the same as issue #42. The behavior is the same with every version of Jitterbug released since VPN feature has been added. I have paid developer account. I have enabled Network Extensions and Virtual Private Networks in developer account settings for Jitterbug’s bundle id as well for it’s tunnelling extension.  Then I was simply sideloading Jitterbug with some basic tool like Sideloadly. This resulted in working VPN and no need of any external tethering. Since the update, VPN does no loger connects. I have tried sideloading with some other software, total unistall and reinstall once again and all avilble versions of VPN-enabled app. At the first glance everything looks okay - local device is detected, I can choose the pairing file. Then iOS shows the dialog that app is going to add vpn connection, which I obviously confirm by PIN. Jitterbug shows up in the vpn list as usual. Then it starts connecting. And… it stucks trying to connect for 30 seconds or so and then connection times out. I have also tried enabling vpn manually with the switch in settings, but it stays enabled only for a factor of a second and immediately bounces back to disabled, it gives you a feeling that totally nothing happened and the operations the switch was designed to trigger aren’t run at all or crash at some preliminary point.
Since then, I was not able to run VPN…
Jitterbug started from another device still works fine for me.
AltStore JIT still works for me.
And JitStreamer ran on my home network still works for me, even through my OpenVPN gateway.
Other VPNs I use, including my corporate VPN, home VPN and some other installed along with APpStore apps, sall of them are still working perfectly fine.
I am using 15.4 dmg image provided by both other mentioned solutions (the images are grabbed automatically on runtime, both are identical), and they obviously support  15.4.1 when mounted and attached to the same device using other mentioned hacks.

I am wondering if this is an issue with app capabilities, but I have confirmed that I enabled them correctly when VPN was working and never changed them since then + i think it is not a signature problem as it would prevent the app from adding its VPN to system VPNs list - but this still seems to compete just fine.
Oh, and last but not least, I was mangling with Jitterbug’s VPN IPs which can be configured with settings, but that didn’t help in any way.

**Comment by osy** [comment] 2022-05-19 22:14
Did you follow the troubleshooting tips on the release page? Regenerate the pairing file?

**Comment by esgie** [comment] 2022-05-19 22:19
I have regenerated pairing files multiple times.
I have also tried utilizing pairing file generated when pairing with JitStreamer, which is still valid and works perfectly fine with JetStreamer even now.

**Comment by dzaikos** [comment] 2022-06-10 07:39
I think this issue needs to be re-opened. I am experiencing the same issue and it is definitely distinct from #42.

I have a paid developer account. I downloaded the source `git clone --recursive https://github.com/osy/Jitterbug.git`. I open the project in XCode, update the developer and bundle IDs, then build it (Network Entitlement and Personal VPN are enabled) with the destination being my iPad Air (running iPadOS 15.5). On my Mac I airdrop the developer disk image and signature (for version 15.5) from inside the XCode.app package to the iPad. I generate a pairing file with jitterbugpair and airdrop that to the iPad.

When I launch Jitterbug on the iPad it loads and I'm able to import the pairing file and developer disk image and signature files. When I tap the Launcher tab I get the prompt to install the VPN, which I accept and confirm with the device passcode. When I select the device from the list, Jitterbug spends about 30 seconds attempting to start the VPN only to report the error that the VPN tunnel failed to connect.

**Comment by esgie** [comment] 2022-08-02 15:14
Indeed it was a signature error.
It seems that common sideloading software available for Windows, including Sideloadly, is no longer able to sign pre-built Jitterbug ipa (the VPN extension in particular) for iOS 15+ so the VPN works - even with developer account and entitlements set up properly and working for iOS14-
This is most likely not a problem if you own Mac, as XCode handles creating and exporting developer certs and provisioning profiles as well as code signing on it’s own, but it is a problem if you are limited only to Windows/Linux computers.
I was finally able to run Jitterbug with VPN working on both 15.x and 16.x beta by manually creating private key and certificate request with bare openssl, then requesting new Apple developer certificate via Apple developer web page, combining that stuff with distribution cert and converting to p12 format (I can cover the details if someone need it, at least it was more elegant way to obtain files needed for signing under Windows than using AltStore with hacked dll… which in fact seems to produce p12 not compliant with new requirements for iOS15+ at all…), creating an appropriate provisioning profile via webpage again... Then I was able to use the files to sign and install Jitterbug ipa on-device using Esign app (sideloaded with Sideloadly) avail at https://esign.yyyue.xyz/ - btw I found it so much easier to use than hosting the whole signing service connected with Github Actions as described somewhere in the comments (I guess there may be some safety and privacy reasons for taking an effort to configure the latter!! It seems signing can be also done under Linux with some tools like zsign but I haven’t tried that).
All in all, I was able to run Jitterbug along with VPN feature with my paid developer account so it works on iOS15+, without owning a Mac

**Comment by startergo** [comment] 2023-06-30 14:32
I am not sure if I understand correctly, but everywhere in the guides a second device running jitterbug is needed. All I did was I used my UDID registrations credentials and iOS App signer with ```No get-task-allow``` unchecked for sign/resign the app. Then downloaded jitterbug.ipa with iOS-deploy to the iPad. Created a paring profile and imported it along with the iOS 16.5 Developer Disk Image and signature files to the iPad. Ran Jitterbug local device tunnel. Opened jitterbug.ipa on the iPad and selected pair. After pairing I can open UTM in tethered mode from within the iPad.
Is this expected behavior or am I doing something wrong? No need for a second device correct?
