### ISSUE TITLE
Use VPN while on cell data

### ISSUE THREAD

**Issue by BenjyWiener** [osy/Jitterbug#44] opened 2022-02-02 23:15 UTC
Currently launching apps via VPN only works while connected to a WiFi network.

It should be possible to get it to work when on cell data by turning on Personal Hotspot and connecting to 172.20.10.1. (I've confirmed that you don't need any devices connected by running a local HTTP server with Pythonista.)

Entering the IP address manually doesn't work, presumably because Jutterbug doesn't try to connect via the VPN.

**Comment by osy** [comment] 2022-02-02 23:55
Duplicate of #23

**Closed** 2022-02-02 23:55 UTC
Labels: duplicate
